#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: owE3/938beS69+GrcoUeRrwpZASerX84uc/6TJGmmF0lioBGkpetXtLWpC7oakTH

# version format
version: 0.1.{build}

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\VL.2D.Voronoi

branches:
  only:
    - master

only_commits:
  message: /build/

install:
  - nuget sources add -Name vvvv -Source http://teamcity.vvvv.org/guestAuth/app/nuget/feed/_Root/default/v3/index.json
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

after_build:
  - nuget pack appveyor\VL.2D.Voronoi.nuspec -Version %APPVEYOR_BUILD_VERSION%-alpha
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.2D.Voronoi\VL.2D.Voronoi.%APPVEYOR_BUILD_VERSION%-alpha.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

test: off

notifications:

  # Email
  - provider: Email
    to:
      - devvvvs@vvvv.org
    subject: 'VL.2D.Voronoi Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true